[package]
name = "mailviewer"
version = "1.0.15"
edition = "2021"
authors = ["Alexandre Del Bigio"]
description = "GNOME eml and Outlook msg file viewer"
readme = "README.md"
repository = "https://github.com/alescdb/mailviewer"
license = "GPL-3.0+"

[package.metadata.cargo-machete]
ignored = ["gettext-rs"]

[dependencies]
mailviewer-core = { git = "https://github.com/alescdb/mailviewer-core", branch = "main" }
webkit6 = "0.6.1"
gtk4 = { version = "0.11.4", features = ["v4_22", "blueprint"] }
log = "0.4.34"
env_logger = "0.11.11"
adw = { version = "0.9.2", features = ["v1_9"], package = "libadwaita" }
gettext-rs = { version = "0.8.0", features = ["gettext-system"] }
